### ISSUE TITLE
Error when start a Consumer

### ISSUE THREAD

**Issue by anhnam00** [weyoss/redis-smq#14]
Hello admin,
I had a problem with stats.js on line 78. I think need remove comma at the end of the line 77.

> D:\server\chat-server\node_modules\redis-smq\src\stats.js:78
                );
                ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\server\chat-server\node_modules\redis-smq\src\consumer.js:8:22)

**Comment by weyoss** [comment]
Thank you for reporting this issue.
You are having this issue because your are using Node.js v7.x.x. This application is working fine from Node.js version v8.x.x.
I am working on this compatibility issue. For now you can consider to upgrade Node.js to a newer version.

**Comment by weyoss** [comment]
A new release is out. Please upgrade.

**Comment by weyoss** [comment]
Closing as resolved.
