### ISSUE TITLE
monitoring not working

### ISSUE THREAD

**Issue by yurik3zzz** [weyoss/redis-smq#4]
Hi.

The monitoring not working in version 1.0.8, but his work in v1.0.7

> TypeError: Cannot destructure property `queueName` of 'undefined' or 'null'.
    at Object.getKeys (D:\nodeProjects\redissmqcollector\node_modules\redis-smq\src\redis-keys.js:14:29)
    at statsFrontend (D:\nodeProjects\redissmqcollector\node_modules\redis-smq\src\stats-frontend.js:15:29)
    at Server.server.listen (D:\nodeProjects\redissmqcollector\node_modules\redis-smq\src\monitor\index.js:52:31)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1378:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)

Thanks

**Comment by weyoss** [comment]
Thank you for reporting this issue. Version 1.0.9 is out. Please upgrade.

**Comment by weyoss** [comment]
Closing as resolved.
