### ISSUE TITLE
Cannot switch to the same current state

### ISSUE THREAD

**Issue by smdesmet** [weyoss/redis-smq#43]
Since upgrading to the latest version(2.0.11), I always get this error when I failover my redis server.
Error: Can not switch to the same current state.
at switchState (/opt/app-root/src/node_modules/redis-smq/src/power-state-manager.js:19:19)
at Object.goingUp (/opt/app-root/src/node_modules/redis-smq/src/power-state-manager.js:62:13)
at Object.start (/opt/app-root/src/node_modules/redis-smq/src/scheduler.js:219:31)
at Producer.<anonymous> (/opt/app-root/src/node_modules/redis-smq/src/instance.js:46:36)
at Producer.emit (events.js:314:20)
at Producer.<anonymous> (/opt/app-root/src/node_modules/redis-smq/src/instance.js:43:18)
at Producer.emit (events.js:314:20)
at Producer.completeBootstrap (/opt/app-root/src/node_modules/redis-smq/src/instance.js:264:14)
at Producer.<anonymous> (/opt/app-root/src/node_modules/redis-smq/src/instance.js:40:60)
at Producer.emit (events.js:314:20)
at /opt/app-root/src/node_modules/redis-smq/src/instance.js:195:23
at /opt/app-root/src/node_modules/neo-async/async.js:6883:13
at /opt/app-root/src/node_modules/redis-smq/src/instance.js:184:22
at tryCatcher (/opt/app-root/src/node_modules/standard-as-callback/built/utils.js:11:23)
at /opt/app-root/src/node_modules/standard-as-callback/built/index.js:19:49
at processTicksAndRejections (internal/process/task_queues.js:93:5)

Looks like the GOING_UP in the power-state-manager is emitted while it is already UP. I am using ioredis with sentinel support, the failover takes ~10sec.
I haven't seen this issue with version 2.0.0

**Comment by weyoss** [comment]
Thank you for your reporting.
 I am currently investigating this issue. Further updates will be posted later.

**Comment by weyoss** [comment]
The bug causing this issue has been located and fixed. You should upgrade your RedisSMQ installation to the latest version.

**Comment by weyoss** [comment]
Closing as resolved.
