### ISSUE TITLE
Does not work with ioredis-mock

### ISSUE THREAD

**Issue by crobinson42** [weyoss/redis-smq#67]
Integration tests in a project with the following setup fails:

Nod.js v16.10.x
ioredis-mock@7
jest@27.x.x
Typescript v4.4.x

Throws an error that ioredis._default is not a constructor.

**Comment by crobinson42** [comment]
```
ioredis_1.default is not a constructor
TypeError: ioredis_1.default is not a constructor
      at RedisClient.getClient (/users/apple_web_dev_team/projects/node-queue-server/node_modules/redis-smq/dist/src/system/common/redis-client/redis-client.js:73:24)
      at new RedisClient (/users/apple_web_dev_team/projects/node-queue-server/node_modules/redis-smq/dist/src/system/common/redis-client/redis-client.js:42:28)
      at Function.getNewInstance (/users/apple_web_dev_team/projects/node-queue-server/node_modules/redis-smq/dist/src/system/common/redis-client/redis-client.js:392:24)
      at Array.Base.setUpSharedRedisClient (/users/apple_web_dev_team/projects/node-queue-server/node_modules/redis-smq/dist/src/system/common/base.js:19:40)
      at waterfall (/users/apple_web_dev_team/projects/node-queue-server/node_modules/redis-smq/dist/src/system/lib/async.js:70:19)
      at Producer.run (/users/apple_web_dev_team/projects/node-queue-server/node_modules/redis-smq/dist/src/system/common/base.js:85:35)
      at new Producer (/users/apple_web_dev_team/projects/node-queue-server/node_modules/redis-smq/dist/src/system/app/producer/producer.js:42:14)
      at new ProducerFrontend (/users/apple_web_dev_team/projects/node-queue-server/node_modules/redis-smq/dist/src/system/app/producer/producer-frontend.js:10:25)
      at new RedisSMQQueueServiceImpl (/users/apple_web_dev_team/projects/node-queue-server/src/services/Queue/RedisSMQ/index.ts:32:21)
      at /usersapple_web_dev_team/projects/node-queue-server/src/services/Queue/RedisSMQ/test.ts:7:15
      at Promise.then.completed (/users/apple_web_dev_team/projects/node-queue-server/node_modules/jest-circus/build/utils.js:391:28)
      at new Promise (<anonymous>)
      at callAsyncCircusFn (/users/apple_web_dev_team/projects/node-queue-server/node_modules/jest-circus/build/utils.js:316:10)
      at _callCircusHook (/users/apple_web_dev_team/projects/node-queue-server/node_modules/jest-circus/build/run.js:181:40)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at _runTestsForDescribeBlock (/users/apple_web_dev_team/projects/node-queue-server/node_modules/jest-circus/build/run.js:47:7)
      ```

**Comment by weyoss** [comment]
It means that ioredis-mock is not a drop-in replacement for ioredis. 

You have a problem with ioredis-mock.

**Comment by weyoss** [comment]
I haven't tried ioredis-mock. 

I have already an idea about the problem with ioredis-mock. 

But I need to run it.

**Comment by crobinson42** [comment]
ioredis-mock is a drop-in replacement in the jest testing environment. 

I believe the issue with the fact that the bundling configuration output of redis-smq is not compatible with both common.js AND esmodules. Or, the other possibility is that there is a bundled reference to ioredis in the redis-smq published files which if that is the case then it's a bad practice and the package should be bundled with rollup.js and use `autoExternal()` plugin appropriately.
